# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
    
  - name: Research
    url: 'research'
    weight: 20
    
  - name: Publications
    url: 'publications'
 # - name: Conference Presentations
    #url: 'Conferences'
    weight: 30
    
  - name: Awards
    url: '#accomplishments'
    weight: 40
    
  - name: Clinical Experience
    url: '#Clinical Experience'
    weight: 50
    #weight: 50
    
  - name: Community Service
    url: '#Clinical Experience'
    weight: 60
    #weight: 50

  - name: Contact
    url: '#contact'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: files/cv.pdf
    weight: 80
